export const HOME = '/home'
export const JOURNALS = '/home/journals'
export const JOURNALDETAILS = '/home/journalentry/:entryId'
export const JOURNALFORM = '/home/addjournal'
export const BOOKMARKS = '/home/bookmarks'
