export const HOME = '/home'
export const JOURNALS = '/journals'
export const JOURNALDETAILS = '/journalentry/:entryId'
export const JOURNALFORM = '/addjournal'
export const BOOKMARKS = '/saved'
export const EXPLORE = '/explore'
